version: "3"
services:
  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900

  web:
    build: .
    working_dir: /usr/src/app
    depends_on:
      - selenium
    links:
      - selenium