# Generated by Django 4.1 on 2023-03-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ObjectAstronomic", new_name="AstronomicalObject",
        ),
    ]
