# Generated by Django 4.1 on 2023-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_astronomicalobject_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomicalobject",
            name="source_image",
            field=models.CharField(default="", max_length=50, verbose_name="Fonte"),
        ),
    ]
