# Generated by Django 4.1 on 2023-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_astronomicalobject_source_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomicalobject",
            old_name="source_image",
            new_name="image_source",
        ),
        migrations.AddField(
            model_name="astronomicalobject",
            name="date_image",
            field=models.DateField(default="2000-01-01", verbose_name="Data da Imagem"),
        ),
    ]
