# Generated by Django 4.1 on 2023-03-25 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "gallery",
            "0005_rename_source_image_astronomicalobject_image_source_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Astrophotography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "image_source",
                    models.CharField(default="", max_length=50, verbose_name="Fonte"),
                ),
                (
                    "date_image",
                    models.DateField(
                        default="2000-01-01", verbose_name="Data da Imagem"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="pictures/%Y/%m/%d", verbose_name="Foto"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Galáxia", "Galáxia"),
                            ("Aglomerado", "Aglomerado"),
                            ("Estrela", "Estrela"),
                            ("Nebulosa", "Nebulosa"),
                            ("Planeta", "Planeta"),
                        ],
                        default="Outros",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Publicado"),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="AstronomicalObject",),
    ]
